function ANSI_COLOUR() {
	printf '\x1B[%dm' "$1"
}

ANSI_RED=$(ANSI_COLOUR 31)
ANSI_GREEN=$(ANSI_COLOUR 32)
ANSI_YELLOW=$(ANSI_COLOUR 33)
ANSI_CYAN=$(ANSI_COLOUR 36)

ANSI_RESET=$(ANSI_COLOUR 0)
ANSI_BOLD=$(ANSI_COLOUR 1)
